/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_DefaultReversiGameLogic */

#ifndef _Included_sample_DefaultReversiGameLogic
#define _Included_sample_DefaultReversiGameLogic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_DefaultReversiGameLogic_initialize
  (JNIEnv *, jobject);

/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    CheckPossibleMoves
 * Signature: ([[II)V
 */
JNIEXPORT void JNICALL Java_sample_DefaultReversiGameLogic_CheckPossibleMoves
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    UpdateBoard
 * Signature: ([[IIII)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_sample_DefaultReversiGameLogic_UpdateBoard
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint);

/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    CheckLocation
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_sample_DefaultReversiGameLogic_CheckLocation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    IsGameOver
 * Signature: ([[I)Z
 */
JNIEXPORT jboolean JNICALL Java_sample_DefaultReversiGameLogic_IsGameOver
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    DeclareWinner
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_sample_DefaultReversiGameLogic_DeclareWinner
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    IsPossibleMoveExist
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sample_DefaultReversiGameLogic_IsPossibleMoveExist
  (JNIEnv *, jobject);

/*
 * Class:     sample_DefaultReversiGameLogic
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_DefaultReversiGameLogic_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
